### ISSUE TITLE
Is IBDmix will reuse sites in mask

### ISSUE THREAD

**Issue by zhangjy859** [PrincetonUniversity/IBDmix#10]
Hi, 
sorry for more question, as an intuitive thought, I noticed that the intervals inside the mask region don't seem to be taken into account, but by reading your code, I noticed that IBDmix seems to consider this situation in some special cases, for example, genotype of 2 in archaic and 0 in modern, is it right? Why is this? 

Thanks for your help, please feel free to correct me, if I am not right.

Regrads

Zhang

**Comment by troycomi** [comment]
You are correct.  It is explained in the paper:
> The scores in Table S1 are applied to variants that pass filtering (see Variant Filtering). To be conservative, we do not use excluded variants to determine the evidence for or against IBD. However, we impute the genotype data for modern humans where they are missing and the archaic genome is heterozygous or homozygous for the alternative allele. In particular, discordant homozygotes provide significant evidence against IBD, which adds important information without increasing the false-positive IBD detection rate.

You can also run with more stats to see how often this type of "recovery" occurs.  I believe it is fairly rare.
