### ISSUE TITLE
early 2023; things I have to adjust to run the pipeline when have one population

### ISSUE THREAD

**Issue by SillySabertooth** [PrincetonUniversity/IBDmix#11]
Hi!

I launched the pipeline some time ago, and there were 3 minor things that I changed in the code to get it running, I will try to recall them now. I guess I had them since I launched it for one population though. I write it this way and not as a pull request since I'm not proficient nor git, python, or snakemake. Just to inform people that there might be some issues, maybe it will save some time for other users :moyai: 

1. **Snakefile, 15 line**; without the empty list I had issues with the variable

```
if 'sample_file' in paths:
    populations = glob_wildcards(paths['sample_file']).population
```
to
```
if 'sample_file' in paths:
    populations = glob_wildcards(paths['sample_file']).population
else:
    populations = []  
```
    
         
2. **Snakefile, 25 line**; I guess function all_input works in the not expected way when having one population. I tried to fix it, but ended up just substituting line 103:

`          '{wildcards.population} '`
to
`            '"ALL" '`
 
3. **config.yaml, 47 line**; I guess it should be uncommented to get the result

```
    # remove for no summary, add 0s for no filtering
    # summary_lod:
    #     - 4
```
to
```
    # remove for no summary, add 0s for no filtering
    summary_lod:
         - 4
```
           
4. **config.yaml, 22-28 line**; it's a matter of taste, but I would suggest saving them as _{wildcard}.txt.gz_ and not just _{wildcard}.gz_ :new_moon_with_face: 

Thanks for the snakemake workflow, I had a tough time recalling what's going on (I couldn't recall much since I've never been proficient), but I enjoyed it!

**Comment by biermanr** [comment]
Thank you for your feedback, I'll be looking over the code soon to see how best I can incorporate your suggestions

**Comment by biermanr** [comment]
hi @SillySabertooth, thank you for your notes on what you needed to change in the Snakefile for your use case, I hope it will be helpful to others who use IBDmix in the future. I'm going to close this issue for now, but please re-open if you have any questions/issues.
