### ISSUE TITLE
vcf can be imputed？

### ISSUE THREAD

**Issue by jackzhong1995** [PrincetonUniversity/IBDmix#12]
Hi!

Thanks for the greate tool for detecting archaic segment.
I just wounder can my vcf files can be imputed? If it's bad for ibdmix, i will use the raw vcf, if not, i will use the imputed data as it's file size is smaller.

Best wishes,
Jie.

**Comment by biermanr** [comment]
Hi Jie, glad you're finding IBDmix useful!

I spoke with one of the IBDmix authors and they said "For imputed data, I think it should work if it does not affect the accurate estimates of allele frequency" so I think using imputed data is worth trying.

I would recommend ALSO running the raw VCF as IBDmix should be fast enough to handle large files and comparing the outputs from the imputed vs raw VCF could help you gain confidence in the results.

I'm going to close this issue for now, but feel free to come back and comment if you have any questions or run into any problems.

-Rob
