### ISSUE TITLE
How to filter the result to get high-confidence introgression segments?

### ISSUE THREAD

**Issue by jackzhong1995** [PrincetonUniversity/IBDmix#13]
Dear Rob!
I have a new question here! After running ibdmix, I'm seeking guidance on how to filter the results for unusually long Denisovan introgression segments. Previous research indicated that individuals typically carry 1-2 megabases (Mb) of Denisovan-derived sequences. However, in my dataset, including populations such as CHB, CHS,  I've observed an unexpected 7-9 Mb of Denisovan ancestry, which seems disproportionate and requires a rational explanation.
Do you have any idea?
Best wishes
Jie.

**Comment by biermanr** [comment]
Hi Jie, I've reached out to the team to see if this is a situation that others have observed before. I'll get back to you when I know more.

**Comment by biermanr** [comment]
Hi Jie, I got this response, I hope it helps:

> In Chen et al, Cell, 2020, we did filter the unusually Denisovan calls which were identified in Africans. Specifically, when an IBDmix call (with Neanderthal reference) overlaps with IBDmix calls in Africans with Denisovan reference, we masked them as they are likely to be false positives. I suggest you performed this filter in your dataset, and it may reduce some amount of detected Denisovan ancestry in your dataset. However, in Chen, et al, Cell, 2020, we didn't distinguish the real introgressed segments among Denisovan calls due to Neanderthal introgression or Deinisovan introgression in Eurasian individuals. Thus, you may still observe some levels of Denisovan ancestry particularly in European populations, which is still under debate (some papers said they detected Denisovan ancestry in both East Asian and European populations). In the future, we may be able to to be more specific on Denisovan calls using IBDmix, but at this point, maybe you could check our Science paper published in 2016 (S*), and we introduced a method to distinguish the introgressed segments due to Neanderthal introgression or Deinisovan introgression, which maybe a good solution.

**Comment by jackzhong1995** [comment]
> Hi Jie, I got this response, I hope it helps:
> 
> > In Chen et al, Cell, 2020, we did filter the unusually Denisovan calls which were identified in Africans. Specifically, when an IBDmix call (with Neanderthal reference) overlaps with IBDmix calls in Africans with Denisovan reference, we masked them as they are likely to be false positives. I suggest you performed this filter in your dataset, and it may reduce some amount of detected Denisovan ancestry in your dataset. However, in Chen, et al, Cell, 2020, we didn't distinguish the real introgressed segments among Denisovan calls due to Neanderthal introgression or Deinisovan introgression in Eurasian individuals. Thus, you may still observe some levels of Denisovan ancestry particularly in European populations, which is still under debate (some papers said they detected Denisovan ancestry in both East Asian and European populations). In the future, we may be able to to be more specific on Denisovan calls using IBDmix, but at this point, maybe you could check our Science paper published in 2016 (S*), and we introduced a method to distinguish the introgressed segments due to Neanderthal introgression or Deinisovan introgression, which maybe a good solution.

Thanks, I got it.
