### ISSUE TITLE
Doubt about software performance in non-archaic populations

### ISSUE THREAD

**Issue by vicbp1** [PrincetonUniversity/IBDmix#7]
Hi all, 
I am trying to test an hypothesis of gene flow between populations that diverged at least 30kya and with possible gene flow at least 10kya. Do I have to change any parameter of IBDmix or should I use with the default settings?

Thank you in advance!

**Comment by troycomi** [comment]
Sorry for the delay!  I thought I would get pinged if there was a post.

Assuming we are talking about humans, I don't think IBDmix (or any method for detecting introgression) is appropriate for this case. The main issue is a split time of 30kya is an order of magnitude less than among hominin lineages. Thus, ILS would make it hard to detect real “introgression”. Gene flow in this case is perhaps more appropriately referred to as “admixture”.  Another method specifically developed to detect admixture and admixture tracts would be better suited for this situation.
