### ISSUE TITLE
Using IBDmix with other Neanderthal genomes

### ISSUE THREAD

**Issue by arpfennig** [PrincetonUniversity/IBDmix#8]
Hi,

Thanks for developing this tool.

Quick question if I want to run it with a different high-coverage Neanderthal genome (e.g., Vindija33.19 or Chagyrskaya), do I need to adjust the IBDmix parameters (e.g., archaic error rate)?

Thanks,
Aaron

**Comment by troycomi** [comment]
You don’t have to adjust the parameters, but we haven’t really looked carefully at it for other archaic genomes.

Feel free to ask more questions here, but closing the issue for now.
