### ISSUE TITLE
whats is abridged_variants.gz come from？

### ISSUE THREAD

**Issue by zhangjy859** [PrincetonUniversity/IBDmix#9]
Hi，
I noted you upload a file `abridged_variants.gz` in [j.cell.2020.01.012-workflow](https://github.com/PrincetonUniversity/IBDmix/tree/main/j.cell.2020.01.012-workflow), Could you please share some information about how to generated it?

Regrads
Zhang

**Comment by troycomi** [comment]
HI Zhang,

Long story short, it's the minimum set of variants to replicate the CpG mask used in the paper.

> CpGs were masked as in ([Prüfer et al., 2014](https://www.sciencedirect.com/science/article/pii/S0092867420300593?via%3Dihub#bib34)).

Which takes you to [this description](https://www.sciencedirect.com/science/article/pii/S0092867412008318#p0445) but the full dataset with "15 hunter-gatherer genomes" isn't publicly hosted.

Hope that clears it up, otherwise I can ping one of the researchers that may know more.

**Comment by zhangjy859** [comment]
Hi, troy
Thanks for your reply. Sorry for opening this question again. Please allow me to ask a few additional questions. 

As far as I noted, Prüfer et al., 2014 (https://www.nature.com/articles/nature12886) seem to only mention very limited things about cpg mask (include supplement infomation). Is there something I neglected?

I noticed that Benjamin's work on S* in 2014 and 2016 is also use this `15 hunter-gatherer genomes` in cpg mask region, so the purpose of add this file is to include some of the variations that distinguish modern humans from African natives? 

we also noted that Benjamin said 

`We identified CpG sites as in (24) by considering the human reference genome (hg19), 
genomes sequenced by Complete Genomics (15 hunter-gatherer genomes [24] and the 
public data release), and three additional primate genomes (chimpanzee, orangutan, and 
macaque).`

in Benjamin 2014, I think the operation of IBDmix seems to follow the work here, so if the 15 hunter-gatherer genomes is a part of `Complete Genomics`, what is the public data release refer to? is the (part or all) individuals sequenced by Complete Genomics？

Can it be replaced with other source if the data is not public? For example, the variation data of YRI in 1000g

**Comment by troycomi** [comment]
I can't speak to the choice of references or the availability of the Complete Genomics data.  I wasn't able to find it on dbGAP and in an effort to make our exact, published results reproducible, I included the CpG sites in the 15 hunter-gatherer genomes as the abridged_variants.

The choice of masking is entirely up to you.  It is valid to consider all variation in 1000g, just YRI or even just hg19 to construct the CpG mask.  Each have different power and sensitivity; I can't say what would be best.

**Comment by zhangjy859** [comment]
Hi, tory
Thanks for your kind help, I'm a newbie in this field, anyway, your high-quality, reproducible code helped me quickly understand the technology in this field.
Regrads.
--------------原始邮件--------------
发件人："Troy&nbsp;Comi ***@***.***&gt;;
发送时间：2023年2月17日(星期五) 晚上11:29
收件人："PrincetonUniversity/IBDmix" ***@***.***&gt;;
抄送："zhangjy859 ***@***.***&gt;;"Author ***@***.***&gt;;
主题：Re: [PrincetonUniversity/IBDmix] whats is abridged_variants.gz come from？ (Issue #9)
-----------------------------------

 

 
I can't speak to the choice of references or the availability of the Complete Genomics data.  I wasn't able to find it on dbGAP and in an effort to make our exact, published results reproducible, I included the CpG sites in the 15 hunter-gatherer genomes as the abridged_variants.
 
The choice of masking is entirely up to you.  It is valid to consider all variation in 1000g, just YRI or even just hg19 to construct the CpG mask.  Each have different power and sensitivity; I can't say what would be best.
